# Generated by Django 6.0.6 on 2026-07-06 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_name', models.CharField(max_length=100)),
                ('grade_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalHarvest',
            fields=[
                ('local_harvest_id', models.AutoField(primary_key=True, serialize=False)),
                ('harvest_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('market_id', models.AutoField(primary_key=True, serialize=False)),
                ('market_name', models.CharField(max_length=100)),
                ('market_address', models.TextField()),
                ('phone_number', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=100)),
                ('partner_address', models.TextField(blank=True, null=True)),
                ('partner_phone', models.PositiveBigIntegerField()),
                ('start_date', models.DateField()),
                ('contract_duration', models.PositiveIntegerField()),
                ('land_area', models.PositiveIntegerField(null=True)),
                ('partner_status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Rejected', 'Rejected'), ('Inactive', 'Inactive')], default='Pending', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dokumen', models.FileField(upload_to='')),
                ('inspection_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('production_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity_id', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_name', models.CharField(max_length=100)),
                ('shelf_life', models.PositiveIntegerField()),
                ('purchase_price', models.PositiveBigIntegerField()),
                ('selling_price', models.PositiveBigIntegerField()),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.grade')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('inventory_batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('harvest_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('Partner', 'Partner'), ('Local', 'Local')], max_length=10)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.commodity')),
            ],
        ),
        migrations.CreateModel(
            name='LocalHarvestDetail',
            fields=[
                ('local_harvest_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.commodity')),
                ('local_harvest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.localharvest')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerHarvest',
            fields=[
                ('partner_harvest_id', models.AutoField(primary_key=True, serialize=False)),
                ('harvest_date', models.DateField()),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerHarvestDetail',
            fields=[
                ('partner_harvest_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.commodity')),
                ('partner_harvest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.partnerharvest')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('selling_price', models.PositiveIntegerField()),
                ('commodity_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.commodity')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionDetail',
            fields=[
                ('production_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.product')),
                ('production_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.production')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.market')),
            ],
        ),
        migrations.CreateModel(
            name='SaleCommodity',
            fields=[
                ('sale_commodity_id', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_quantity', models.PositiveIntegerField()),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.commodity')),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.grade')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('sale_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.PositiveIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.product')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('reference_type', models.CharField(choices=[('SaleProduct', 'Sale Product'), ('SaleCommodity', 'Sale Commodity'), ('PartnerHarvest', 'Partner Harvest'), ('Cost', 'Cost')], max_length=30)),
                ('reference_id', models.PositiveIntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.transactioncategory')),
            ],
        ),
    ]
