# Generated by Django 6.0.6 on 2026-07-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guava', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='production_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_type',
            field=models.CharField(choices=[('SaleProduct', 'Sale Product'), ('SaleCommodity', 'Sale Commodity'), ('PartnerHarvest', 'Partner Harvest'), ('Cost', 'Cost'), ('Production', 'Production')], max_length=30),
        ),
    ]
