# Generated by Django 6.0.6 on 2026-07-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guava', '0002_product_production_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='source_detail_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
