# Generated by Django 6.0.6 on 2026-07-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guava', '0003_inventorybatch_source_detail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondetail',
            name='sale_product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guava.saleproduct'),
        ),
    ]
