# Generated by Django 6.0.6 on 2026-07-17 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guava', '0004_productiondetail_sale_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUsage',
            fields=[
                ('inventory_usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory_batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.inventorybatch')),
                ('sale_commodity_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guava.salecommodity')),
                ('sale_product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guava.saleproduct')),
            ],
        ),
    ]
