# Generated by Codex on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guava', '0005_inventoryusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_type',
            field=models.CharField(choices=[
                ('Manual', 'Manual'),
                ('SaleProduct', 'Sale Product'),
                ('SaleCommodity', 'Sale Commodity'),
                ('PartnerHarvest', 'Partner Harvest'),
                ('Cost', 'Cost'),
                ('Production', 'Production'),
            ], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
