# Generated by Django 6.0.6 on 2026-07-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guava', '0006_manual_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='dokumen',
            new_name='document',
        ),
    ]
